config/routes.rb
RecGame::Application.routes.draw do
  get "login/:login" => 'login#login'

  get 'users/logout' => 'users#logout'
  resources :users

  resources :results

   root :to => 'welcome#index'

end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :category, :competition, :date, :note, :opp, :opp_score, :place, :score, :team, :win
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  class UnAuthorized < Exception ; end

  attr_accessible :description, :mail, :url, :name, :summary, :categorys_text, :teams_text

  has_many :results, dependent: :destroy, :order => ['date desc', 'created_at desc']

  validates :name, :presence => true,
                   :length => { :maximum => 32}
  validates :mail, :length => { :maximum => 128}
  validates :summary, :length => { :maximum => 140}
  validates :description, :length => { :maximum => 2048}
  validates :categorys_text, :presence => true, :length => { :maximum => 512}
  validates :teams_text, :presence => true, :length => { :maximum => 512}

  def categorys
    categorys_text.split
  end

  def teams(category = nil)
    a = teams_text.split
    if category
      hash = {}
      a.each do |e|
        if e =~ /([^\s]+)::([^\s]+)/
          hash[$1] ||= []
          hash[$1] << $2 
        end
      end
      a = hash[category] if hash[category]
    end
    a.map {|e| e.sub(/[^\s]+::/, '') }
  end

  def category_results(category)
    if category.nil? or category == 'ALL'
      results
    else
      results.where(:category => category)
    end
  end
end

app/controllers/application_controller.rb
# -*- encoding: utf-8 -*-

class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from User::UnAuthorized, :with => -> { render :text => 'ログインしていません.' }

  before_filter { 
    @category = session[:category]
    session[:category] = nil
  }

  private

  def user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
  end

  def login_required
    if session[:user_id]
      @user ||= User.find(session[:user_id])
    else
      raise User::UnAuthorized
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
    @user = User.find_by_login params[:login]
    session[:user_id] = @user.id
  rescue
    render :text => 'Login failed'
  end
end

app/controllers/results_controller.rb
# -*- encoding: utf-8 -*-

class ResultsController < ApplicationController
  before_filter { user }
  before_filter { login_required }
  after_filter {
    session[:category] = @category
  }

  def index
    @category = params[:category] if params[:category]
    @categorys = @user.categorys
    @results = @user.category_results(@category)
  end

  def show
    @result = @user.results.find(params[:id])
  end

  def new
    @result = @user.results.new
    @result.category = @category
    #if last = @user.results.where(:category => @category).order('created_at desc').first
    if last = Result.where(:user_id => @user, :category => @category).order('created_at desc').first
      @result.competition = last.competition
      @result.place = last.place
      @result.team = last.team
    end
  end

  def edit
    @result = @user.results.find(params[:id])
  end

  def create
    @result = @user.results.new(params[:result])
    @result.win = if @result.score > @result.opp_score then '◯'
                  elsif @result.score < @result.opp_score then '☓'
                  else '△' end
    if @result.save
      redirect_to results_url, notice: 'Result was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @result = @user.results.find(params[:id])

    if @result.update_attributes(params[:result])
      redirect_to results_url, notice: 'Result was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @result = @user.results.find(params[:id])
    @result.destroy

    redirect_to results_url
  end
end

app/controllers/users_controller.rb
# -*- encoding: utf-8 -*-

class UsersController < ApplicationController
  include LoginHelper

  def logout
    session[:user_id] = nil
    redirect_to users_url
  end

  def index
    @users = User.all
  end

  def show
    @current_user = User.find(params[:id])
    @categorys = @current_user.categorys
    @category = params[:category] || 'ALL'
    @results = @current_user.category_results(@category)
  end

  def new
    @new_user = User.new
  end

  def edit
    login_required
    raise User::UnAuthorized unless @user == User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    @user.login = rand(1000000000000).to_s(36)
    # 本当はここに日本語メッセージを書くのは良くない
    @user.categorys_text = "高学年\n中学年\n低学年\n幼児クラス"
    @user.teams_text = "6年\n5年\n4年\n3年\n2年\n1年\n幼児"
    if @user.save
      redirect_to login_url, notice: 'User was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    login_required
    if @user.update_attributes(params[:user])
      redirect_to login_url, notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    login_required
    raise User::UnAuthorized unless @user == User.find(params[:id])
    @user.destroy

    redirect_to users_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
  def login_url
    "/login/#{@user.login}"
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def rowspans_table(rows, colum_name)
    rowspans = []
    skip_ct = 0
    rows.each_with_index do |row, i|
      if skip_ct > 0
        skip_ct -= 1
        next
      end
      nxt = if i < rows.size - 1
              rows[i + 1].send(colum_name)
            else
              nil
            end
      if !nxt.blank? and nxt == row.send(colum_name)
        n = 0
        rows[i..-1].each {|e| e.send(colum_name) == nxt ? n += 1 : break }
        rowspans[i] = n
        skip_ct = n - 1
      else
        rowspans[i] = 1
      end
    end
    rowspans
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! XML
!!! 1.1
%html{"xml:lang" => "ja", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title== 得点くん#{@subtitle}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  %body{ :class => controller_name }
    %div.main
      %div.content
        = yield

      .footer
        %hr
        - if @user
          %p.right
            = link_to "ログインしています: #{@user.name}", login_url
        %p
          tokutenkun.net :
          このサイトは<b>#{link_to '得点くん', '/'}</b>で作られています

app/views/login/login.html.haml
%h1 管理画面: #{@user.name}


%p 今開いているページがログインページなりますので、忘れないようブックマークをお願いします。

%p このページのURLは他人に知られないようご注意ください。

%h3 メニュー

%ul
  %li= link_to '試合結果を追加・編集', results_path
  %li= link_to 'チーム情報を編集', edit_user_path(@user)
  %li= link_to "#{@user.name}の公開ページ", @user
  %li= link_to "ログアウト", users_path + '/logout'

app/views/results/_form.html.haml
= form_for @result do |f|
  -if @result.errors.any?
    #error_explanation
      %h2= "#{pluralize(@result.errors.count, "error")} prohibited this result from being saved:"
      %ul
        - @result.errors.full_messages.each do |msg|
          %li= msg
  - is_new = action_name == 'new'
  - if is_new
    = f.hidden_field :category
  %table
    - unless is_new
      %tr
        %td= f.label :category
        %td= f.select :category, @user.categorys
    %tr
      %td= f.label :date
      %td= f.date_select :date
    %tr
      %td= f.label :team
      %td= f.select :team, @user.teams(@result.category)
    - unless is_new
      %tr
        %td= f.label :win
        %td= f.select :win, %w(◯ × △ -)
    %tr
      %td= f.label :score
      %td= f.select :score, 0..20
    %tr
      %td= f.label :opp_score
      %td= f.select :opp_score, 0..20
    %tr
      %td= f.label :opp
      %td= f.text_field :opp
    %tr
      %td= f.label :competition
      %td= f.text_field :competition
    %tr
      %td= f.label :place
      %td= f.text_field :place
    %tr
      %td= f.label :note
      %td= f.text_area :note, :size => '40x4'
  .actions
    = f.submit 'Save'

app/views/results/_list.html.haml
- is_editing = controller_name == 'results'

%p
  カテゴリ選択:
  - [@categorys, 'ALL'].flatten.each do |category|
    - if category == @category
      %b= category
    - else
      = link_to category, request.path_info + "?category=#{category}"

- if is_editing
  - if @category.nil? or @category == 'ALL'
    %p= "結果を追加するにはカテゴリを選択してください"
  - else
    %p= link_to "#{@category}の結果を追加", new_result_path

%table.results
  %tr
    %th=t 'result.category'
    %th=t 'result.date'
    %th=t 'result.team'
    %th=t 'result.win'
    %th=t 'result.score'
    %th=t 'result.opp'
    %th=t 'result.competition'
    %th=t 'result.place'
    %th=t 'result.note'
    - if is_editing
      %th
      %th

  - place_rowspans = rowspans_table(@results, :place)
  - compe_rowspans = rowspans_table(@results, :competition)
  - @results.each_with_index do |result, i|
    %tr
      %td.center.nowrap= result.category
      %td.center.nowrap= result.date
      %td.center.nowrap= result.team
      %td.center.nowrap= result.win
      %td.center.nowrap
        = result.score
        = '-'
        = result.opp_score
      %td= result.opp
      - unless compe_rowspans[i].nil?
        %td{:rowspan => compe_rowspans[i]}= result.competition
      - unless place_rowspans[i].nil?
        %td{:rowspan => place_rowspans[i]}= result.place

      %td= result.note
      - if is_editing
        %td.nowrap= link_to '編集', edit_result_path(result)
        %td.nowrap= link_to '削除', result, :confirm => 'Are you sure?', :method => :delete

app/views/results/edit.html.haml
%h1 試合結果を編集

= render 'form'

= link_to 'Back', results_path

app/views/results/index.html.haml
%h1
  試合結果編集
  = @user.name
  = @category if @category

= render 'list'

app/views/results/new.html.haml
%h1 #{@result.category}の試合結果を新規入力

= render 'form'

= link_to 'Back', results_path

app/views/results/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @result.date
%p
  %b Team:
  = @result.team
%p
  %b Opp:
  = @result.opp
%p
  %b Score:
  = @result.score
%p
  %b Opp score:
  = @result.opp_score
%p
  %b Competition:
  = @result.competition
%p
  %b Place:
  = @result.place
%p
  %b Note:
  = @result.note

= link_to 'Edit', edit_result_path(@result)
\|
= link_to 'Back', results_path

app/views/users/_form.html.haml
- user = @new_user || @user
= form_for user do |f|
  -if user.errors.any?
    #error_explanation
      %h2= "#{pluralize(user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - user.errors.full_messages.each do |msg|
          %li= msg

  %table
    %tr
      %td
        = f.label :name
        %span.presence ※必須
      %td= f.text_field :name
    %tr
      %td
        = f.label :mail
        %span.presence ※必須
      %td= f.text_field :mail
    %tr
      %td= f.label :summary
      %td= f.text_field :summary
    - if action_name == 'edit' or action_name == 'update'
      %tr
        %td= f.label :url
        %td= f.text_field :url
      %tr
        %td
          = f.label :categorys_text
          %span.presence ※必須
          %p.example
            例）低学年 幼稚園等
          %p.example
            カテゴリ分けが不要な場合は
            %br
            団体名を入力しておいてくだ
            %br
            さい。
            %br
            例）横浜FC
        %td= f.text_area :categorys_text, :size => '20x8'
      %tr
        %td
          = f.label :teams_text
          %span.presence ※必須
          %p.example
            団体内のチームを定義します。
            %br
            例）一軍 二軍 1年 2年-A等
        %td= f.text_area :teams_text, :size => '20x8'
      ==<!--
      %tr
        %td= f.label :description
        %td= f.text_area :description
      ==-->
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 チーム情報の編集

= render 'form'

= link_to 'Back', login_url

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Mail
    %th Login
    %th Summary
    %th Description
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= link_to user.name, "/login/#{user.login}"
      %td= user.mail
      %td= user.login
      %td= user.summary
      %td= user.description
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 チーム新規作成

= render 'form'

app/views/users/show.html.haml
- @subtitle = ": #{@current_user.name}の試合結果"

%h1 #{@current_user.name}の試合結果

%p#notice= notice

- unless @current_user.summary.blank?
  %p.summary
    = @current_user.summary
    - url = @current_user.url
    - if url and !url.empty?
      = link_to '» ホームページ', url

%div.description
  = @current_user.description

= render '/results/list'

app/views/welcome/index.html.haml
%h1 得点くん

%p
  サービス開始から
  %b #{Result.count}試合
  の結果が入力されました！

%h2 少年サッカーや少年野球チームの試合結果の記録を、シンプルに。

%p 「得点くん」はサッカーや野球のチームをはじめとする、スポーツチームの試合記録を支援するサービスです。
%p だれでも手軽に利用できる、簡単でシンプルなWebサービスを目指しています！

%h2 新規登録

%p= link_to '» チームを新規登録する', '/users/new'